# Required connection configs for Kafka producer, consumer, and admin
bootstrap.servers=pkc-7prvp.centralindia.azure.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=WPCWVW2LEOXHIQFP
sasl.password=cfltOnBkKguREeo9GNvIXOXKSDrCoeFXI3ERqeIsI6re0ssj03v+b4UwjiFE68CA

# Best practice for higher availability in librdkafka clients prior to 1.7
session.timeout.ms=45000

client.id=ccloud-python-client-63642c38-fd25-4662-a0be-d439764703b5
